export const types = {
  CHECKOUT_WALLETS: '@@initialPage/CHECKOUT_WALLETS',
  MOUNT_WALLETS: '@@initialPage/MOUNT_WALLETS',
  CREATE_WALLET: '@@initialPage/CREATE_WALLET',
  DELETE_WALLET: '@@initialPage/DELETE_WALLET',
  SELECT_WALLET: '@@initalPage/SELECT_WALLET',
  FETCH_WALLET_INFO: '@@initalPage/FETCH_WALLET_INFO',
  MOUNT_WALLET_INFO: '@@initalPage/MOUNT_WALLET_INFO',
  FETCH_TOTAL_BALANCE: '@@initialPage/FETCH_TOTAL_BALANCE',
  MOUNT_TOTAL_BALANCE: '@@initialPage/MOUNT_TOTAL_BALANCE',
  MOUNT_HISTORY: '@@initialPage/MOUNT_HISTORY',
  CHECKOUT_HISTORY: '@@initialPage/CHECKOUT_HISTORY',
};
