export const types = {
  CHECKOUT_WALLETS: '@@walletList/CHECKOUT_WALLETS',
  MOUNT_WALLETS: '@@walletList/MOUNT_WALLETS',
  CREATE_WALLET: '@@walletList/CREATE_WALLET',
  DELETE_WALLET: '@@walletList/DELETE_WALLET',
  UPDATE_WALLET_LIST: '@@walletList/UPDATE_WALLET_LIST',
  FETCH_WALLET_INFO: '@@walletList/FETCH_WALLET_INFO',
  MOUNT_WALLET_INFO: '@@walletList/MOUNT_WALLET_INFO',
  UPDATE_WALLET_BY_WID: '@@walletList/UPDATE_WALLET_BY_WID',
};
