export const types = {
  FETCH_COURSE: "@@fiat/FETCH_COURSE",
  MOUNT_COURSE: "@@fiat/MOUNT_COURSE",
  MOUNT_FIAT: "@@fiat/MOUNT_FIAT",
  FETCH_COURSE_COMISSION: "@@fiat/FETCH_COURSE_COMISSION",
  MOUNT_COURSE_COMISSION: "@@fiat/MOUNT_COURSE_COMISSION"
};
