export const types = {
  CHECK_OUT_INITIAL: "@@wallet/CHECK_OUT_INITIAL",
  GET_DATA_FOR_CHART: "@@wallet/GET_DATA_FOR_CHART",
  MOUNT_DATA_FOR_CHART: "@@wallet/MOUNT_DATA_FOR_CHART",
  GET_WALLET: "@@wallet/GET_WALLET",
  FETCH_WALLET_INFO: "@@wallet/FETCH_WALLET_INFO",
  MOUNT_WALLET_INFO: "@@wallet/MOUNT_WALLET_INFO",
  FECTH_TRANSACTIONS: "@@wallet/FECTH_TRANSACTIONS",
  MOUNT_TRANSACTIONS: "@@wallet/MOUNT_TRANSACTIONS",
  GET_WALLET_IN_GAIA: "@@wallet/GET_WALLET_IN_GAIA",
  MAKE_TRANSACTION: "@@wallet/MAKE_TRANSACTION",
  GET_FIAT_CURRENCY: "@@wallet/GET_FIAT_CURRENCY",
  MOUNT_FIAT: "@@wallet/MOUNT_FIAT",
  MOUNT_TRX_ID: "@@wallet/MOUNT_TRX_ID",
  FETCH_TOKEN_INFO: "@@wallet/FETCH_TOKEN_INFO",
  MOUNT_TOKEN_INFO: "@@wallet/MOUNT_TOKEN_INFO",
  UPDATE_WALLET_BY_ADDRESS: "@@wallet/UPDATE_WALLET_BY_ADDRESS"
};
