export const types = {
  CHECKOUT_WALLETS: '@@dashboard/CHECKOUT_WALLETS',
  MOUNT_WALLETS: '@@dashboard/MOUNT_WALLETS',
  CREATE_WALLET: '@@dashboard/CREATE_WALLET',
  DELETE_WALLET: '@@dashboard/DELETE_WALLET',
  SELECT_WALLET: '@@dashboard/SELECT_WALLET',
  FETCH_WALLET_INFO: '@@dashboard/FETCH_WALLET_INFO',
  MOUNT_WALLET_INFO: '@@dashboard/MOUNT_WALLET_INFO',
  FETCH_TOTAL_BALANCE: '@@dashboard/FETCH_TOTAL_BALANCE',
  MOUNT_TOTAL_BALANCE: '@@dashboard/MOUNT_TOTAL_BALANCE',
  MOUNT_HISTORY: '@@dashboard/MOUNT_HISTORY',
  CHECKOUT_HISTORY: '@@dashboard/CHECKOUT_HISTORY',
};
